//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArcherConnectIAMEntities : DbContext
    {
        public ArcherConnectIAMEntities()
            : base("name=ArcherConnectIAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrgPerson> OrgPersons { get; set; }
        public virtual DbSet<OrgType> OrgTypes { get; set; }
        public virtual DbSet<OrgTypeAssignment> OrgTypeAssignments { get; set; }
        public virtual DbSet<SystemRole> SystemRoles { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<SystemUserRole> SystemUserRoles { get; set; }
        public virtual DbSet<Bankruptcy> Bankruptcies { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Claimant> Claimants { get; set; }
        public virtual DbSet<DomainPerson> DomainPersons { get; set; }
        public virtual DbSet<Lien> Liens { get; set; }
        public virtual DbSet<Medical_Record> Medical_Record { get; set; }
        public virtual DbSet<OrgPermission> OrgPermissions { get; set; }
        public virtual DbSet<SystemObjectPermission> SystemObjectPermissions { get; set; }
        public virtual DbSet<SystemPermission> SystemPermissions { get; set; }
        public virtual DbSet<SystemPerson> SystemPersons { get; set; }
        public virtual DbSet<SystemRolePermission> SystemRolePermissions { get; set; }
        public virtual DbSet<UI_Element> UI_Elements { get; set; }
        public virtual DbSet<UI_Module> UI_Modules { get; set; }
        public virtual DbSet<UI_Module_Element> UI_Module_Elements { get; set; }
        public virtual DbSet<vw_AvailableModulePermission> vw_AvailableModulePermission { get; set; }
        public virtual DbSet<vw_Claimant> vw_Claimant { get; set; }
        public virtual DbSet<vw_EffectiveOrgPermission> vw_EffectiveOrgPermission { get; set; }
        public virtual DbSet<vw_EffectiveRolePermission> vw_EffectiveRolePermission { get; set; }
        public virtual DbSet<vw_EffectiveUserPermission> vw_EffectiveUserPermission { get; set; }
        public virtual DbSet<vw_OrgPerson> vw_OrgPerson { get; set; }
        public virtual DbSet<vw_OrgTypeAssignment> vw_OrgTypeAssignment { get; set; }
        public virtual DbSet<vw_OrgUser> vw_OrgUser { get; set; }
        public virtual DbSet<vw_SystemObjectPermission> vw_SystemObjectPermission { get; set; }
        public virtual DbSet<vw_UserRole> vw_UserRole { get; set; }
        public virtual DbSet<vw_EffectiveRolePermission_DomainData> vw_EffectiveRolePermission_DomainData { get; set; }
        public virtual DbSet<vw_DomainData> vw_DomainData { get; set; }
    }
}
