//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgTypeAssignment
    {
        public int Id { get; set; }
        public Nullable<int> Organization { get; set; }
        public Nullable<int> OrganizationType { get; set; }
        public string Name { get; set; }
    }
}
