//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AvailableModulePermission
    {
        public Nullable<System.Guid> ModuleElementObjectID { get; set; }
        public string elementName { get; set; }
        public string ModuleName { get; set; }
        public string PermissionId { get; set; }
        public string PermissionName { get; set; }
        public int SystemObjectPermissionId { get; set; }
    }
}
