//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Claimant
    {
        public int ClaimantId { get; set; }
        public Nullable<System.Guid> ObjectID { get; set; }
        public Nullable<int> domainpersonid { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string ssn { get; set; }
    }
}
