//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EffectiveUserPermission
    {
        public int SystemUserId { get; set; }
        public string Username { get; set; }
        public string ElementName { get; set; }
        public string ModuleName { get; set; }
        public string PermissionName { get; set; }
        public string PermissionType { get; set; }
    }
}
