//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EffectiveRolePermission_DomainData
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public int SystemRolePermissionId { get; set; }
        public Nullable<int> systemObjectPermissionID { get; set; }
        public string DataType { get; set; }
        public string PermissionName { get; set; }
        public Nullable<System.Guid> objectId { get; set; }
        public string name { get; set; }
    }
}
