//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcherConnect_IAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SystemObjectPermission
    {
        public int ModuleElementId { get; set; }
        public Nullable<System.Guid> ModuleElementObjectId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ElementId { get; set; }
        public Nullable<int> SystemObjectPermissionID { get; set; }
        public Nullable<int> PermissionId { get; set; }
        public string PermissionName { get; set; }
    }
}
