//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deleteme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPermission
    {
        public int Id { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsWrite { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public string Name { get; set; }
    }
}
